apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      version: v2
  template:
    metadata:
      labels:
        app: mysql
        version: v2
    spec:
      containers:
      - name: mysql
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        image: tmarkunin/maria:2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
